export const FILTER_BEGIN = 'FILTER_BEGIN';
export const FILTER_SUCCESS = 'FILTER_SUCCESS';
export const FILTER_FAILED = 'FILTER_FAILED';


export const CHART_BEGIN = 'CHART_BEGIN';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const CHART_FAILED = 'CHART_FAILED';


export const TABLE_BEGIN = 'TABLE_BEGIN';
export const TABLE_SUCCESS = 'TABLE_SUCCESS';
export const TABLE_FAILED = 'TABLE_FAILED';