export const TABLE_FILTERS_INIT = 'TABLE_FILTERS_INIT';
export const TABLE_FILTERS_INIT_SUCCESS = 'TABLE_FILTERS_INIT_SUCCESS';
export const TABLE_FILTERS_UPDATE_VALUE = 'TABLE_FILTERS_UPDATE_VALUE';
export const TABLE_FILTERS_SEARCH = 'TABLE_FILTERS_SEARCH';

export const TABLE_DATA_INIT = 'TABLE_DATA_INIT';
export const TABLE_DATA_ASSIGN = 'TABLE_DATA_ASSIGN';
